# Site 网站
title: MountMount~!
subtitle: Mount.的冷藏库
description: 只是一个备忘录, 用来记录一些我认为有用的东西
language: zh-CN
timezone: Asia/Shanghai
author: Mount.

# 文章
post_asset_folder: true

# 扩展
theme: next

# 插件
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-' 作者：两条小鱼 https://www.bilibili.com/read/cv15174123/ 出处：bilibili
